language: php

notifications:
  email:
    on_success: never

php:
  - 7.4

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: dependencies=lowest

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install -n
  - docker-compose up -d
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script:
  - vendor/bin/phpunit
